AWSTemplateFormatVersion: '2010-09-09'
Description: Macumba Password Manager
Parameters:
  MacumbaBucketName:
    Default: macumba-secrets
    Type: String
Resources:
  MacumbaAPICreatePassword:
    Properties:
      CodeUri: s3://macumba-lambda/17b3755c8eea3ebf0fa88d221cd4a11a
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME: macumba-secrets
      Events:
        CreatePassword:
          Properties:
            Method: post
            Path: /api/v1/secret
          Type: Api
      Handler: macumba_pass.web.application
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - cloudwatch:*
          Effect: Allow
          Resource: '*'
        Version: 2012-10-17
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${MacumbaBucketName}
        Version: 2012-10-17
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${MacumbaBucketName}/*
        Version: 2012-10-17
      Runtime: python3.6
    Type: AWS::Serverless::Function
  MacumbaAPIIndex:
    Properties:
      CodeUri: s3://macumba-lambda/17b3755c8eea3ebf0fa88d221cd4a11a
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME: macumba-secrets
      Events:
        APIIndex:
          Properties:
            Method: get
            Path: /
          Type: Api
      Handler: macumba_pass.web.application
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - cloudwatch:*
          Effect: Allow
          Resource: '*'
        Version: 2012-10-17
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${MacumbaBucketName}
        Version: 2012-10-17
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${MacumbaBucketName}/*
        Version: 2012-10-17
      Runtime: python3.6
    Type: AWS::Serverless::Function
  MacumbaAPIRetrievePassword:
    Properties:
      CodeUri: s3://macumba-lambda/17b3755c8eea3ebf0fa88d221cd4a11a
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME: macumba-secrets
      Events:
        RetrievePassword:
          Properties:
            Method: get
            Path: /api/v1/secret
          Type: Api
      Handler: macumba_pass.web.application
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - cloudwatch:*
          Effect: Allow
          Resource: '*'
        Version: 2012-10-17
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${MacumbaBucketName}
        Version: 2012-10-17
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${MacumbaBucketName}/*
        Version: 2012-10-17
      Runtime: python3.6
    Type: AWS::Serverless::Function
  MacumbaBucket:
    Properties:
      AccessControl: Private
      BucketName:
        Ref: MacumbaBucketName
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
