AWSTemplateFormatVersion: '2010-09-09'
Description: Macumba Password Manager
Parameters:
  MacumbaBucketName:
    Default: macumba-secrets
    Type: String
Resources:
  MacumbaAPICreatePassword:
    Properties:
      CodeUri: s3://macumba-lambda/5b2f7211d4fad71a1c4d2202aef711a5
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME:
            Ref: MacumbaBucketName
      Events:
        CreatePassword:
          Properties:
            Method: post
            Path: /api/v1/secret
          Type: Api
      Handler: macumba_pass.web.application
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::${MacumbaBucketName}
        Version: '2012-10-17'
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::${MacumbaBucketName}/*
        Version: '2012-10-17'
      Runtime: python3.6
    Type: AWS::Serverless::Function
  MacumbaAPIIndex:
    Properties:
      CodeUri: s3://macumba-lambda/5b2f7211d4fad71a1c4d2202aef711a5
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME:
            Ref: MacumbaBucketName
      Events:
        APIIndex:
          Properties:
            Method: get
            Path: /
          Type: Api
      Handler: macumba_pass.web.application
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${MacumbaBucketName}
        Version: '2012-10-17'
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${MacumbaBucketName}/*
        Version: '2012-10-17'
      Runtime: python3.6
    Type: AWS::Serverless::Function
  MacumbaAPIRetrievePassword:
    Properties:
      CodeUri: s3://macumba-lambda/5b2f7211d4fad71a1c4d2202aef711a5
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME:
            Ref: MacumbaBucketName
      Events:
        RetrievePassword:
          Properties:
            Method: get
            Path: /api/v1/secret
          Type: Api
      Handler: macumba_pass.web.application
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::${MacumbaBucketName}
        Version: '2012-10-17'
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::${MacumbaBucketName}/*
        Version: '2012-10-17'
      Runtime: python3.6
    Type: AWS::Serverless::Function
  MacumbaBucket:
    Properties:
      AccessControl: Private
      BucketName: macumba-secrets
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
