AWSTemplateFormatVersion: '2010-09-09'
Description: Macumba Password Manager
Parameters:
  MacumbaBucketName:
    Type: String
Resources:
  MacumbaBucket:
    Properties:
      AccessControl: Private
      BucketName: macumba-secrets
    Type: AWS::S3::Bucket
  MacumbaRESTfulAPI:
    Properties:
      CodeUri: s3://macumba-lambda/0e1e295b5868e423f25a39461bee5aab
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME:
            Ref: MacumbaBucketName
      Events:
        APIIndex:
          Properties:
            Method: get
            Path: /
          Type: Api
        CreatePassword:
          Properties:
            Method: post
            Path: /api/v1/secret
          Type: Api
        RetrievePassword:
          Properties:
            Method: get
            Path: /api/v1/secret
          Type: Api
      Handler: macumba_pass.web.application
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::${MacumbaBucketName}
        Version: '2012-10-17'
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::${MacumbaBucketName}/*
        Version: '2012-10-17'
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
