AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Macumba Password Manager

Parameters:
  MacumbaBucketName:
    Type: String
    Default: macumba-secrets

Resources:
  MacumbaBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref MacumbaBucketName

  MacumbaAPIIndex:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/
      Handler: macumba_pass.web.application
      Runtime: python3.6
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME: macumba-secrets

      Policies:
        - AWSLambdaExecute
        - Version: 2012-10-17
          Statement:
            - Resource: "*"
              Effect: Allow
              Action:
                - 'cloudwatch:*'

        - Version: 2012-10-17
          Statement:
            - Resource: !Sub 'arn:aws:s3:::${MacumbaBucketName}'
              Effect: Allow
              Action:
                - 's3:*'

        - Version: 2012-10-17
          Statement:
            - Resource: !Sub 'arn:aws:s3:::${MacumbaBucketName}/*'
              Effect: Allow
              Action:
                - 's3:*'

      Events:
        APIIndex:
          Type: Api
          Properties:
            Path: /
            Method: get

  MacumbaAPICreatePassword:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/
      Handler: macumba_pass.web.application
      Runtime: python3.6
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME: macumba-secrets

      Policies:
        - AWSLambdaExecute
        - Version: 2012-10-17
          Statement:
            - Resource: "*"
              Effect: Allow
              Action:
                - 'cloudwatch:*'

        - Version: 2012-10-17
          Statement:
            - Resource: !Sub 'arn:aws:s3:::${MacumbaBucketName}'
              Effect: Allow
              Action:
                - 's3:*'

        - Version: 2012-10-17
          Statement:
            - Resource: !Sub 'arn:aws:s3:::${MacumbaBucketName}/*'
              Effect: Allow
              Action:
                - 's3:*'
      Events:
        CreatePassword:
          Type: Api
          Properties:
            Path: /api/v1/secret
            Method: post

  MacumbaAPIRetrievePassword:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/
      Handler: macumba_pass.web.application
      Runtime: python3.6
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME: macumba-secrets
      Policies:
        - AWSLambdaExecute
        - Version: 2012-10-17
          Statement:
            - Resource: "*"
              Effect: Allow
              Action:
                - 'cloudwatch:*'

        - Version: 2012-10-17
          Statement:
            - Resource: !Sub 'arn:aws:s3:::${MacumbaBucketName}'
              Effect: Allow
              Action:
                - 's3:*'

        - Version: 2012-10-17
          Statement:
            - Resource: !Sub 'arn:aws:s3:::${MacumbaBucketName}/*'
              Effect: Allow
              Action:
                - 's3:*'
      Events:
        RetrievePassword:
          Type: Api
          Properties:
            Path: /api/v1/secret
            Method: get
