Resources:
  MacumbaBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: private
      BucketName: macumba-secrets

  MacumbaAPIIndex:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/
      Handler: macumba_pass.web.application
      Runtime: python3.6
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME: macumba-secrets
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: 'arn:aws:s3:::macumba-secrets'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: 'arn:aws:s3:::macumba-secrets/*'
      Events:
        APIIndex:
          Type: Api
          Properties:
            Path: /
            Method: get


  MacumbaAPICreatePassword:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/
      Handler: macumba_pass.web.application
      Runtime: python3.6
      Environment:
        Variables:
          MACUMBA_BUCKET_NAME: macumba-secrets
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: 'arn:aws:s3:::macumba-secrets'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: 'arn:aws:s3:::macumba-secrets/*'
      Events:
        CreatePassword:
          Type: Api
          Properties:
            Path: /api/v1/password
            Method: post

        RetrievePassword:
          Type: Api
          Properties:
            Path: /api/v1/password
            Method: get
