sequenceDiagram
    participant DEV as Developer
    participant TERM as Terminal Console
    participant WEB as Chalise Application
    participant TASK as CloudWatch Task

    Note over DEV,TASK: >>> ipdb.set_trace()
    DEV->TERM: on main TTY
    TERM->>WEB: make run
    Note over DEV,WEB: $ make run

    DEV->TERM: on another TTY
    TERM->>WEB: run smoke tests
    Note over DEV,WEB: $ make smoke
    TERM-->>WEB: HTTP Request
    Note over DEV,TASK: curl -H POST http://localhost:3000/shipment/book -d < ./tests/smoke/booking-payload.json
    DEV->TASK: Debug away!
